### ISSUE TITLE
Blender 2.9 - Error with annotation and _PT_ suffix

### ISSUE THREAD

**Issue by Draise14** [leukbaars/DreamUV#9]
![image](https://user-images.githubusercontent.com/35357409/86686356-e59fac80-bfc9-11ea-8c7d-ea74e49d4e41.png)

Tried it out with Blender 2.9, and I get these errors in the console and the panel won't register.

**Comment by leukbaars** [comment]
I have only tested this on 2.83 so far, I'll support 2.9 once it gets closer to release. I've found it to be a lot of work trying to keep up with experimental builds

**Comment by Draise14** [comment]
AH, makes sense. Been using 2.9 builds for a while now. I guess I'll wait! Thanks for the great addon.

**Comment by ThatAsherGuy** [comment]
These warnings aren't exclusive to 2.90, but I think most of them are a red herring. The annotation warnings can be fixed with a basic find and replace (use a colon instead of an equals sign when you declare properties), and the panel name formatting warning is mostly cosmetic.

For the actual issue, I'd work backwards from when/how you register `DUVUVToolsPreferences`

**Comment by leukbaars** [comment]
Thanks guys, it sounds pretty straightforward to fix up. I'll have a look at it tonight
There's a lot of old things commented out that I need to clean up :).

**Comment by leukbaars** [comment]
i finally cleaned this up!
